apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stae
  labels:
    app: myapp
spec:
  serviceName: stae
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: state-container
          image: mysql:5.7
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123

---
apiVersion: v1
kind: Service
metadata:
  name: stae
  labels:
    app: myapp
spec:
  clusterIP: None
  selector:
    app: myapp
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306